### ISSUE TITLE
Image URL sharing

### ISSUE THREAD

**Issue by nwtn** [ResponsiveImagesCG/ri-usecases#11]
Need to consider possible use cases and/or requirements and/or notes about how copying and sharing image URLs would work given multiple sources (and possibly multiple formats).

See comments from Josh Fraser @ Torbit:

> The biggest problem we ran into that we didn't expect is the number of people who grab the URL of the image and share it on Facebook, Twitter, email, whatever.  This of course breaks for everyone not using a browser that supports it.  We can serve the images up each time from a single URL based on the User-Agent, but that's not something you can do at the browser level.

**Comment by marcoscaceres** [comment]
Linked to this from the spec.

**Comment by lilith** [comment]
I suggest that all current menu items (Like Open Image in New Tab, Copy Image Link) behave as if the current 'image' was the only URL, for clarity and obviousness. 

While I DO anticipate user frustration of lack of format support in other browsers, I think that will help motivate browser vendors to follow through with implementations. To open the door to new formats, we DO have to solve first-level adoption issues through type="content/type". But this issue isn't serious enough to stall adoption, and if things are too smooth, IE will never support WebP :)

I do suggest mentioning that user agents MAY introduce a contextual menu listing "Alternate Image Versions" as source URIs, which when clicked causes  the selected version to be opened in a new tab, window, or popup.

**Comment by anselmh** [comment]
If img-element is provided as fallback that would be the easiest solution. Provide this URL to the user.

If not it should be the one that is actually displayed by the browser to the user. This case the user gets what he actually sees and does not have to download more sources.

**Comment by igrigorik** [comment]
@nathanaeljones yet, the inability to have a safe fallback for WebP is exactly what prohibits more sites from adopting it. A 30% savings over JPEG is a _huge_ deal for the mobile web.

To address the root issue, we probably need both browser UI and markup tweaks: browser UI for user sharing, and markup for bookmarklets and extensions which simply scan the DOM, looking for images.

**Comment by anselmh** [comment]
Revised my thoughts and came to the result that it always should be the mobile / small version which should be shared if it actually is not a html-responsive file. That due to the fact mobile traffic is more and more limited by providers…

**Comment by nwtn** [comment]
I agree with @nathanaeljones that the ideal scenario would be for browsers to alter the context-menu options, allowing users to select which source they want to open/copy/save. That might be a tall order though, and I'm not sure how much we can push for it in our specs.

It's possible that confusion that arises out of this could, as @nathanaeljones said, push browser makers towards better/more implementations. However, it's also possible that it could push developers to abandon the whole thing to avoid this frustration.

If new context menu options aren't available, I'm not totally sure of the best approach; my thinking on this has flip-flopped a couple times. Right now I'm leaning towards the browser using the URL of the image that is currently displayed. It's the most predictable for users. If it used, as @anselmh suggests, the fallback image (or the mobile/small version), the user might end up getting a version with different art direction, or of a different size, and I think that's problematic.

**Comment by igrigorik** [comment]
What you're describing is content negotiation, which should be handled at a lower layer. In fact, this is nothing new: some clients may support gzip, some not, and the format is negotiated at request time, transparent to the user. 

Instead of adding context menu's, etc, the browser can instead send an `Accept` header indicating which image formats it supports, at which point the URL stays the same, but encoding changes.

**Comment by nwtn** [comment]
@igrigorik this isn't just for image formats, though, it's an issue for different size images and differently art-directed images, too. It needs to be predictable to the user what image they're copying. Ideally, it would also give them the choice.

**Comment by igrigorik** [comment]
You're copying what you're seeing, providing a client mechanism to arbitrarily swap out the resource when you want to copy or share it is a great vector for abuse and nasty attacks - aka, art-direction in the opposite direction. If you want the user to share a different resource, then provide a link to the alternate version.

**Comment by Wilto** [comment]
I’m with @igrigorik here. I’m certain there are ways this could be handled really cleverly on the UA side, but one step at a time—for our purposes, I think speccing that the currently visible source is the “sharable” one is the most we can do for now.

**Comment by nwtn** [comment]
@igrigorik That's an interesting point about it being a potential attack/abuse vector

@Wilto as I said, I'm leaning this way too right now. I think a new context menu is a good idea but, as I said, I don't think it's something we can push for in the specs.

**Comment by anselmh** [comment]
@igrigorik @Wilto Agree. We should do it that way now for the spec. The other things are up to UA/UA-plugins.

**Comment by MattWilcox** [comment]
My thinking is that it'd be nice for the browser UI to expose alternative resources, but the use case is someone sharing what they can see. So to me it makes sense that the behaviour would be to grab the URI for whatever asset the user is being shown.

**Comment by marcoscaceres** [comment]
I can't see any further action here relating to the use cases. Let's come back to this if we need to later.
