### ISSUE TITLE
Need better art direction diagram

### ISSUE THREAD

**Issue by marcoscaceres** [ResponsiveImagesCG/ri-usecases#12]
The current Art Direction figure in the spec is not ideal. It would be nice to have a diagram that both explains the concept and is, itself, also responsive (when used with picturefill).

**Comment by jeremyworboys** [comment]
Changed tact: http://d.pr/i/lqfH

It's simple, explains the concept and is background independent. Working on arranging it in a way that we can make it responsive.

**Comment by ShaneHudson** [comment]
Is it worth using one or two non Apple products to demonstrate that it really is cross platform?

**Comment by Wilto** [comment]
+1 to chucking a couple of non-Apple screen sizes in there.

**Comment by marcoscaceres** [comment]
It was mentioned in IRC that explicitly using any company's products explicitly won't win us any friends. We should be vendor neutral in all our work.

**Comment by jeremyworboys** [comment]
Just caught the convo on IRC. Here is an updated copy with a Nook tab and a generic Droid: http://d.pr/i/yH8N

**Comment by ShaneHudson** [comment]
Thanks Jeremy, I think that gets the point across much better, 
responsive means works across all devices, not just some brands :)

Jeremy Worboys wrote:

**Comment by marcoscaceres** [comment]
Looks like we are getting there. @jeremyworboys, can you please move the psd file into the [images directory](https://github.com/ResponsiveImagesCG/ri-usecases/tree/gh-pages/images) on the gh-pages branch. That way, we can collaborate on it.

Some notes: 
- I think we need a better picture that more clearly shows what is being "art directed"
- we should remove identifying marks on devices, including buttons.
- at least one device should be in portrait mode.

**Comment by anselmh** [comment]
Agree with Marcos. 
Also I think we should add a Kindle / Kobo with Monochrome image-type. For the crops an image like the Obama-one works much better. Or provide two images. The more examples we have the easier it is to understand.

**Comment by marcoscaceres** [comment]
Instead of adding another device, we can probably just make one of the images monochrome inside one of the devices. That will get the point across.

**Comment by jeremyworboys** [comment]
I'm thinking maybe throw another device or two in there and lay them out horizontally next to each other. We can then cut off the outer devices for art direction when displaying this image. Based on this the outer devices should not be important for conveying the message.

**Comment by anselmh** [comment]
IMO it must not contain another device. I just think the monochrome part is an important feature of respimg and Kindle is the first device people understand why it would be useful.

**Comment by ghost** [comment]
Could someone please explain what "art direction" is?

**Comment by marcoscaceres** [comment]
@mahroof-ali please see: http://usecases.responsiveimages.org/#art-direction . If that text doesn't make sense, then we need to fix it. It's that text that we are trying to convey as an image.

**Comment by marcoscaceres** [comment]
I've updated to use the following image (thanks @wilto!). However, the image has a few problems, namely the image shown in the picture is clearly not "responsive", otherwise the text in the image ("there is life out there") would be legible at a small size : 

<img src="https://github.com/ResponsiveImagesCG/responsiveimages.org/blob/master/css/_img/devices.png?raw=true" width="800" height="500" style="max-width:800px" class="stretchy">

@Wilto, could you possibly provide the device frames from the image as a PSD? We could then build all sorts of really nice images from those.

**Comment by Wilto** [comment]
From IRC discussion: the lead background image on responsiveimages.org is going to be swapped out for a content image, paired with a description. The Dribbble screenshot above is showing Picturefill in use, though Dribble is only using it for resolution switching. This is a good opportunity to finally get some “in the wild” examples of the `picture` pattern showcased on the site, along with a brief write-up of how it’s being used.

(@hellogeri, have we gotten permission from whoever posted that Dribbble shot? Else, we can use one of ours.)

**Comment by hellogeri** [comment]
@Wilto We don't have permission, but I can likely get it pretty quickly (or, use one of ours like you said!)

**Comment by marcoscaceres** [comment]
@Wilto, @hellogeri, rotating banner graphic? _always fresh_ :tm:

**Comment by marcoscaceres** [comment]
Ok, <img src=http://usecases.responsiveimages.org/images/art_direction.jpg>

**Comment by Kusadam** [comment]
#57 [http://kusadam.com/hediye](url)
