### ISSUE TITLE
Document is not mobile friendly

### ISSUE THREAD

**Issue by marcoscaceres** [ResponsiveImagesCG/ri-usecases#17]
The images and video are not being correctly sized for mobile.

**Comment by Wilto** [comment]
If only there were a way to load screen-appropriate images!

Looking into this now.

**Comment by Wilto** [comment]
Mobile-friendlier as of 15d346d468b3a6435a0e5d5480c94e87ea704853

**Comment by marcoscaceres** [comment]
Much better! Tested on iOS (iPad 2 and iPhone) and on Android 2.2..
