### ISSUE TITLE
XSS attack <script>console.warm('pwned')</script>

### ISSUE THREAD

**Issue by marcoscaceres** [ResponsiveImagesCG/ri-usecases#21]
Because we were not sanitizing the titles of Github bugs, we left ourselves open to a XSS attack. @marcoscaceres tried to fix this with: 

>  htmlspecialchars($var, ENT_QUOTES, 'UTF-8').

But he is no PHP security expert.

**Comment by marcoscaceres** [comment]
Need to fix this ASAP

**Comment by marcoscaceres** [comment]
Ok, I think I fixed it with: htmlspecialchars($var, ENT_QUOTES, 'UTF-8'). 

However, need security review.

**Comment by marcoscaceres** [comment]
testing again

**Comment by marcoscaceres** [comment]
Seems ok now, but would really like a proper review. Maybe @attiks can do it or knows someone? The file in question is: https://github.com/ResponsiveImagesCG/responsiveimages.org/blob/master/issues.php#L86 (`print_issues()` function)

**Comment by attiks** [comment]
did you push the latest changes?

**Comment by marcoscaceres** [comment]
ah, my bad. I did not. I only pushed to the website... pushing now.

**Comment by marcoscaceres** [comment]
https://github.com/ResponsiveImagesCG/responsiveimages.org/commit/aee6f2484f50371ecb89d8f7e3a9c4688793c8d1

**Comment by attiks** [comment]
That should do it.
