### ISSUE TITLE
Find out what we need to do to go to W3C FPWD

### ISSUE THREAD

**Issue by marcoscaceres** [ResponsiveImagesCG/ri-usecases#23]
The group is feeling pretty good about the document now, so we are ready to hopefully move it to the HTMLWG. 

See also: https://github.com/ResponsiveImagesCG/ri-usecases/issues/24

**Comment by marcoscaceres** [comment]
Emailed Ian Jacobs at W3c for guidance. Will post progress soon.

**Comment by marcoscaceres** [comment]
Ian's response. 

> Sure. By the way, I talked about this a bit during TPAC (see slides [1]) and know I need to write up some documentation. I am taking notes here:
> http://www.w3.org/community/council/wiki/Transition_to_the_W3C_standards_track
> 
> First, let's talk about patent commitments. When all the companies in the CG are also in the WG, it's a non-issue. But if there are people who are making substantive contributions to the CG report who are NOT in the WG, then:
> 
> a) They should consider joining the WG (but they may not want to due to other patent commitments that would
> trigger)
> b) You should get them to sign the Final Specification Agreement if you can. That will increase confidence about the spec published by the WG.
> 
> Second, it's ok for the CG to continue to work on the spec. The HTML WG should publish updated drafts periodically, which will continue to "refresh" the content over which people in the WG make commitments.
> 
> Lastly, the CG does not need to get final specifications on an ongoing basis since I think the WG commitments are the more important ones. But as the spec matures and approaches Candidate Recommendation, then I think it would be good to get people to give FSA commitments over the CG draft that is published as the WG Candidate Recommendation, since that document is more likely to go all the way to Recommendation, and thus you want the most commitments possible over that draft.
> 
> Note that from a copyright perspective, the HTML WG can publish the CG document at any time. However, we want the WG and CG to be happy with the situation, so the groups should obviously be in sync on the plan.
> 
> Does that help?
> Ian

**Comment by marcoscaceres** [comment]
@Wilto you went through this once before with the first publication. What buttons did you press, etc.?

**Comment by marcoscaceres** [comment]
I [emailed the HTMLWG also](http://lists.w3.org/Archives/Public/public-html/2012Nov/0173.html). I don't expect any response, but worth a try.

**Comment by marcoscaceres** [comment]
@Wilto ping:

> you went through this once before with the first publication. What buttons did you press, etc.?

**Comment by Wilto** [comment]
Hm. I had an option on http://www.w3.org/community/respimg/ before—it doesn’t give me the option to republish or anything. I think so far as the push for FPWD goes, we would just want to put it up to the HTMLWG list a la http://lists.w3.org/Archives/Public/public-html/2012Nov/0129.html

I don’t know if we can do so ourselves, or if we’ll have to pester someone in the HTMLWG to do it for us. This might be a question for Adrian.

**Comment by marcoscaceres** [comment]
(@wilto emailed Ian Jacobs for instructions... setting to "waiting on")

**Comment by marcoscaceres** [comment]
Ok, clarity! 

1) The CG cannot publish on /TR/, only the HTML Working Group can.
- To do this, the editor of the spec formats the document according to "pubrules" [1] and then Mike Smith (the Team Contact) sends a "transition request" according to the publication process [2]. (When you visit [1] and [2] you need to pick First Public Working Draft from the dropdown to see the requirements for that step.)
- The "transition request" goes to the Director (actually Ralph Swick). He does a sanity check of the situation and
  then approves it. Then Mike Smith sends a "publication request" to our Webmaster, who makes it appear on /TR/.
- It may be that someone else in the WG besides Mike Smith can send the transition and publication requests,
  but I recommend chatting with Mike since he has experience doing this with the HTML WG.

2) Regarding patent commitments, it looks like you've already secured "Final Spec Agreement (FSA) Commitments" from a number of people for the Picture Element:
http://www.w3.org/community/respimg/spec/26/commitments

If you believe you have commitments from all the real contributors, then you can just point the HTML WG
at this list and say "Here are the final specification commitments we have received. As Chair, I believe these
cover the material contributions to the specification."

Suppose they come back to you and say "Wait a minute! It looks like Microsoft, Opera, Mozilla, and other
companies have not signed the FSA!" You can respond "That's ok. Those organizations are in the HTML
Working Group. So as soon as the Working Group publishes the First Public Working Draft, those organizations
will be making commitments over the Working Group's version of the document."

So you should identify any individuals or companies participating in the CG that are NOT also participating in the
HTML Working Group. If they have not yet made an FSA Commitment, contact them and insist.

3) Regarding copyright, there's nothing to do.

**Comment by marcoscaceres** [comment]
see also: https://github.com/ResponsiveImagesCG/ri-usecases/issues/24

**Comment by marcoscaceres** [comment]
All of the above are now done. I've emailed @sideshowbarker (Mike Smith, W3C team contact for W3C) for a check on how to proceed from here. The documents are at: 

http://usecases.responsiveimages.org/pub/WD_15Jan2013.html
http://picture.responsiveimages.org/pub/WD_15Jan2013.html
