### ISSUE TITLE
Get commitments from CG members

### ISSUE THREAD

**Issue by marcoscaceres** [ResponsiveImagesCG/ri-usecases#24]
We need to get IPR commitments from CG members before we publish. 

They need to click on red button: 
http://www.w3.org/community/respimg/spec/26/commitments

**Comment by marcoscaceres** [comment]
@Wilto this looks to me like something a Chair would take care of :monkey:.

**Comment by Wilto** [comment]
Quick! To the Chair… uh, chair!

**Comment by marcoscaceres** [comment]
Thanks @Wilto [emailing the list](http://lists.w3.org/Archives/Public/public-respimg/2012Dec/0024.html)! 

Lets give it a week and then contact any stragglers. My understanding is that we don't need everyone, just people who have made significant contributions that have ended up on the spec.

**Comment by Wilto** [comment]
I think we’re good on this for now, yeah? We can reopen/revisit if anyone thinks we need to ping anyone specific or push for more.

**Comment by marcoscaceres** [comment]
WFM. The main thing is that the main contributors have signed it.
