### ISSUE TITLE
Art direction use case description should be more than cropping

### ISSUE THREAD

**Issue by grigs** [ResponsiveImagesCG/ri-usecases#25]
The current description for art direction says:

> In a responsive design, it is typical to change the crop of an image so it can be targeted towards the features of a particular display (or set of displays)

The Nokia example shown later demonstrates that sometimes the changes aren’t simply cropping. 

Perhaps we could change it to say something like:

“In a responsive design, it is typical to change an image so it can be targeted towards the features of a particular display (or set of displays). Sometimes this means cropping an image. Other times, it can mean a new form of an image that may have different proportions or may be changed in other ways to match changes in the layout.”

**Comment by yoavweiss** [comment]
@marcoscaceres the change doesn't show up at http://usecases.responsiveimages.org/.
Did I modify the wrong branch?

**Comment by anselmh** [comment]
Think it has to be merged manually to show up on website.
