### ISSUE TITLE
Resolution switching illustration is misleading

### ISSUE THREAD

**Issue by grigs** [ResponsiveImagesCG/ri-usecases#28]
I don’t see much difference between:
http://usecases.responsiveimages.org/images/devices.png

And the illustration being used to illustrate the art direction use case:
http://usecases.responsiveimages.org/images/art_direction.jpg

Cropping appears to happen in both examples even if the cropping is more pronounced in the art direction example. If you just look at the two examples side by side, it would be hard to figure out why they were different without the associated content.

I think it would be better to have an example where the resolution switching illustration kept its aspect ratio through all of the sizes of the image.

**Comment by marcoscaceres** [comment]
@grigs I agree. A better set of images would be better. Could you possibly provide them? I can then put them into the device frames.

**Comment by nwtn** [comment]
i'd suggest not using the device frames, as it will make either cropping or letterboxing necessary. something like http://www.andreasnorman.com/wp-content/uploads/2012/04/retina-example.png might be more appropriate for resolution switching.

**Comment by yoavweiss** [comment]
Anyone interested in picking this issue up?

**Comment by yoavweiss** [comment]
closed by https://github.com/ResponsiveImagesCG/ri-usecases/pull/38
