### ISSUE TITLE
Clarify explanatory statement about WebP/Jpeg vs PNG.

### ISSUE THREAD

**Issue by lilith** [ResponsiveImagesCG/ri-usecases#29]
Perhaps change "the PNG format is better-suited to these needs." to "the PNG and WebP lossless formats are better-suited to these needs."? 

WebP Lossless offers [faster decoding than PNG, and 25-30% smaller file sizes](https://developers.google.com/speed/webp/docs/webp_lossless_alpha_study).

**Comment by marcoscaceres** [comment]
Added. Change set: 
https://github.com/ResponsiveImagesCG/ri-usecases/commit/c72e908cb36134738fd7b9c39bfdfd9d98b8b31c
