### ISSUE TITLE
"breakpoints" undefined

### ISSUE THREAD

**Issue by miketaylr** [ResponsiveImagesCG/ri-usecases#3]
In 3.2 Design Breakpoints, "breakpoints" is used, but never defined, e.g., "Developers currently match specific CSS Media Queries "breakpoints" for images to the breakpoints that they have defined in the CSS of their responsive designs."

Following the "CSS Media Queries" link, there is no definition there either.

Typically breakpoints are used to refer to stopping program execution for debugging, so some clarification here would be good.

**Comment by miketaylr** [comment]
I guess there's an implicit definition here:

```
If a breakpoint in the design is specified in [CSS21] as:

@media screen (max-width: 41em) {}
```

Still I think an explicit definition would be good.

**Comment by marcoscaceres** [comment]
Agreed. I'll add it (or remove it)... breakpoint is a bit of an "industry term" (it's just a media query after all!). 

How does this sound? 

> In Web development, a breakpoint is one of a series of CSS Media Queries that update the styles of a page based on matching some media features. Breakpoints generally form a logical set of rules that target, for example, predictable device widths so covering a gamut of potential devices (e.g., first mobile phones, then smart phones, then tablets, then desktop monitors, then high resolution displays, and so on).

**Comment by miketaylr** [comment]
Beauty, Bob.

**Comment by Wilto** [comment]
I think we could go even more simple with it. How about something like:

> In Web development, a “breakpoint” is one of a series of CSS Media Queries that update the styles of a page based on information about the client’s browsing context. A single breakpoint represents a logical rule (or set of rules) determining the point at which the contents of a media query are applied to a page’s layout.

**Comment by marcoscaceres** [comment]
@Wilto going to meet you half way. I want to keep the first sentence in my definition because it's using language straight out of the media queries spec. However, your second sentence is nice and clear :)

**Comment by Wilto** [comment]
Sounds good to me.
