### ISSUE TITLE
Add additional solution requirements

### ISSUE THREAD

**Issue by lilith** [ResponsiveImagesCG/ri-usecases#30]
11 The solution SHOULD offer an method to leverage breakpoints defined in CSS.
12 The solution SHOULD support a simplified syntax to support primary use case 3.1 (preferably a list of images and their dimensions), in order to reach users of content management systems and those without detailed knowledge of device queries.

As [a complete solution to these requirements exists](https://gist.github.com/nathanaeljones/5047077), and these requirements have been expressed repeatedly by a large variety of contributors on the respimg mailing list, these requirements should be considered for inclusion.

**Comment by marcoscaceres** [comment]
Although I don't disagree with the general sentiment of the proposed requirements, I feel they are overly prescriptive. Also 11 is very close to requirement 1, which already reads:

> 1. The solution MUST afford developers the ability to match image sources with particular media features and/or media types.

CSS and breakpoints are implied in as a media feature.  And also, 6:

> The solution MUST afford developers the ability to define the breakpoints for images as either minimum values (mobile first) or maximum values (desktop first) to match the media queries used in their design.

If there are no objections, I would like to close this bug.

**Comment by marcoscaceres** [comment]
err, I mean, if there are objections, please re-open the bug.

**Comment by lilith** [comment]
The purpose of 11 is to allow layout logic/presentation  to be externalized, not just for them to support CSS media queries. It isn't related to the purpose of 1.

The goal of 12 is to support GUIs and less knowledgeable authors. I've been getting an increasing quantity of feedback from real-world users of proponents of responsive images that they do not intend to use &lt;picture> (as it stands) in the future, even if it is implemented, due to the required complexity. 

If 'srcset' develops the ability to specify mime-types and retains dimension specifications, this might be OK. IMHO, however, narrowing the gap between 'srcset' and 'picture' is best accomplished by allowing simpler usage of 'picture' instead of making srcset more complicated.

The two big issues with 'srcset' are: 1. Readability, writability, and parseability is terrible with real URLs. 2. Doesn't solve our image formats problem; lack of mime-type specification is still holding back progress with image formats.

**Comment by marcoscaceres** [comment]
On Friday, 15 March 2013 at 12:52, Nathanael Jones wrote:

> The purpose of 11 is to allow layout logic/presentation to be externalized, not just for them to support CSS media queries. It isn't related to the purpose of 1.

That's not clear from what you wrote. Or, at least, I didn't get it.  

> The goal of 12 is to support GUIs and less knowledgeable authors. I've been getting an increasing quantity of feedback from real-world users of proponents of responsive images that they do not intend to use <picture> (as it stands) in the future, even if it is implemented, due to the required complexity.

It would be great if you could bring them here to comment. We have 216 people in the CG + 1042 followers on twitter and very few have raised serious concerns about the design. There are also several sites using picturefill without issues. This is not to say that there are no problems with the design, just that we are getting a different message from people. 

> If 'srcset' develops the ability to specify mime-types and retains dimension specifications, this might be OK. IMHO, however, narrowing the gap between 'srcset' and 'picture' is best accomplished by allowing simpler usage of 'picture' instead of making srcset more complicated.

Can't argue with that :)  

> The two big issues with 'srcset' are: 1. Readability, writability, and parseability is terrible with real URLs.

Agree. But we have no control over that as it's a WHATWG controlled proposal. . 

> 1. Doesn't solve our image formats problem; lack of mime-type specification is still holding back progress with image formats.

Agree, also. Hixie doesn't buy the argument that we need a new format hence the this is unlikely to change unless browser vendors throw some support behind this. To date, this has not happened. 

See: https://www.w3.org/Bugs/Public/show_bug.cgi?id=20214
