### ISSUE TITLE
Modify the relative units section

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/ri-usecases#32]
The relative units section in the use-cases document doesn't define the problem well IMO. The linked article is preferring the use of EMs because of an old WebKit bug impacting zoom+/- on px based MQs, that was since fixed.

The real reason EM based breakpoints should be preferred in RWD is that the user's font size preferences can impact the MQs, unlike PX based MQs. 

It may also be possible that some devices have em/px ratio other than 16, meaning that they may look broken if breakpoints are set in px only.

**Comment by yoavweiss** [comment]
Waiting for @nwtn to add a matching illustration

**Comment by marcoscaceres** [comment]
Yippy! once we have this we can republish!

**Comment by nwtn** [comment]
I mocked up these images, but I'm not feeling confident that they explain the issue, and I'm not sure what the best way to present them is. Feedback welcome.

![units-px-camera-man-1](https://f.cloud.github.com/assets/786799/1103524/23ff8afe-18b0-11e3-93ce-b9bc2b323fd8.jpg)
![units-px-camera-man-2](https://f.cloud.github.com/assets/786799/1103525/2a2f00b2-18b0-11e3-8ee9-8e0e2b9cafb8.jpg)
![units-px-camera-man-3](https://f.cloud.github.com/assets/786799/1103526/2e2098d4-18b0-11e3-95e4-0ef8edcbc82e.jpg)
![units-em-camera-man-1](https://f.cloud.github.com/assets/786799/1103527/321c3c90-18b0-11e3-94fc-51bc9cabb224.jpg)
![units-em-camera-man-2](https://f.cloud.github.com/assets/786799/1103528/35828f2e-18b0-11e3-9496-821c6803fa62.jpg)
![units-em-camera-man-3](https://f.cloud.github.com/assets/786799/1103529/39c3245e-18b0-11e3-9fdc-759b11ce7194.jpg)
