### ISSUE TITLE
Section 1.1 still has src-N listed as 'in-development' solution

### ISSUE THREAD

**Issue by anselmh** [ResponsiveImagesCG/ri-usecases#53]
http://usecases.responsiveimages.org/ lists src-N as 4th proposal in section 1.1.
While I find the title of the proposal (“Proposal for RespImg Syntax”) very confusing (“src-N Approach” would be better IMO), I think this proposal has been deprecated and shouldn’t be listed here anymore as the section description says it lists all in-development specifications.

**Comment by marcoscaceres** [comment]
I agree we should change the wording, but I think it's nice to keep it in the document because it's a nice piece of the historical record. We should just add a note that src-n is not longer being perused as a solution .

**Comment by anselmh** [comment]
Sure :)
