### ISSUE TITLE
Gather usage evidence 

### ISSUE THREAD

**Issue by marcoscaceres** [ResponsiveImagesCG/ri-usecases#9]
In light of the use case gathering process, I was reading: http://www.codinghorror.com/blog/2008/02/i-repeat-do-not-listen-to-your-users.html

Key bits:

> To discover which designs work best, watch users as they attempt to perform tasks with the user interface. This method is so simple that many people overlook it, assuming that there must be something more to usability testing. [It] boils down to the basic rules of usability:
> - Watch what people actually do.
> - Do not believe what people say they do.
> - Definitely don't believe what people predict they may do in the future.

From which I think we should do run a simple developer challenge (except without using the dicky word "challenge" :) ). 

It would be a simple test like: "using either picture or img@srcset, show us how you would make this image responsive". And we provide 3 images.

We could learn a lot from it to see what syntax developers prefer to solve the problem. We would need about 400+ responses for the survey to be statistically valid.

**Comment by anselmh** [comment]
What about asking via poll?
Don't understand what you mean by your 2nd test method.
Also I do think both ways are use-cases and both are used depending on what type of website and what types of images one uses for the website.

**Comment by marcoscaceres** [comment]
@anselmh the problem with a poll is that we won't get representative results (see ["I Repeat: Do Not Listen to Your Users"](http://www.codinghorror.com/blog/2008/02/i-repeat-do-not-listen-to-your-users.html))... particularly:

>  "Watch what people actually do" 

What we to actually see _how_ people solve the responsive images problem in code (i.e., do they use img@srset or picture, and how do they use them). Ideally, we could find enough examples in the wild to do this, but we would need about 400 samples to be statistically representative. That's too much work, so setting up a "challenge" would be better to gather a good sampling of data.

**Comment by anselmh** [comment]
Thanks for explaining a bit more in depth, Marcos. If you need help with this, just notify me.

**Comment by marcoscaceres** [comment]
@anselmh yeah, the original bug description is not very clear. It was a random thought at 2am on a saturday night :) I'll update it to try to make it more clear. 

I've started making some "paper prototypes" ([pdf](https://dl.dropbox.com/u/38490906/proto1.pdf))... I'll make a few more and upload them to github.

**Comment by marcoscaceres** [comment]
updated description

**Comment by marcoscaceres** [comment]
During today's call, @Wilto was not convinced we should gather this evidence. I'm ok to close this and come back to it in the future.
